# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI (2.x)

on:
  push:
    branches: [2.x]
  pull_request:
    branches: [2.x]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Source
        uses: actions/checkout@v2

      - name: Copy Dist To VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_NAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "./dist"
          target: "~/template/vue-h5-template/2.x"

      # - name: Remote ssh && Deploy
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_NAME }}
      #     key: ${{ secrets.SSH_KEY }}
      #     script: |
      #       cd /root/template/vue-h5-template
      #       git checkout dev
      #       git pull
      #       npm install --registry=https://registry.npm.taobao.org
      #       npm run build
